client_secret: 2h1TEmM79EPLBctbNrd014hWlkZ3Sr26
debug: false
disable_auto_update: false
disable_command_execute: false
disable_force_update: false
disable_nat: false
disable_send_query: false
gpu: false
insecure_tls: false
ip_report_period: 1800
report_delay: 3
self_update_period: 0
server: kcystufkiiuc.ap-northeast-1.clawcloudrun.com:443
skip_connection_count: false
skip_procs_count: false
temperature: false
tls: true
use_gitee_to_upgrade: false
use_ipv6_country_code: false
uuid: 45017112-2c36-4e45-97df-32be659311b0
